Fix rubocop rules for all repos
When running in guest-house or vincari-rails, we get an error when
trying to run `./bin/test` using the settings in the `.rubocop.yml`
file.

```
== Linting ==
.rubocop-https---raw-githubusercontent-com-ComplyMD-dotfiles-master--rubocop-yml:
Metrics/LineLength has the wrong namespace - should be Layout
Error: obsolete `EnforcedStyle: rails` (for
Layout/IndentationConsistency) found in
.rubocop-https---raw-githubusercontent-com-ComplyMD-dotfiles-master--rubocop-yml
`EnforcedStyle: rails` has been renamed to `EnforcedStyle: indented_internal_methods`
```

These changes update that.